FROM image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas101839-0811-das1.6-py3.10-20250812-beta

# add vllm kubernetes plugin support
# COPY dist/vllm_kubernetes_plugin-0.1.0.tar.gz /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz
# RUN pip install /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz --no-deps && rm -rf /tmp/vllm_kubernetes_plugin-0.1.0.tar.gz

# add vllm tei plugin support
COPY dist/vllm_tei_plugin-0.9.2.tar.gz /tmp/vllm_tei_plugin-0.9.2.tar.gz
RUN pip install /tmp/vllm_tei_plugin-0.9.2.tar.gz --no-deps && rm -rf /tmp/vllm_tei_plugin-0.9.2.tar.gz

ENTRYPOINT ["python3", "-m", "vllm_tei_plugin.entrypoints.openai.api_server"]